import streamlit as st
import duckdb
import pandas as pd
import os

st.set_page_config(page_title="Data Mission Dashboard", layout="wide")

DB_PATH = "data_mission.duckdb"

def load_data():
    if not os.path.exists(DB_PATH):
        return None
    
    con = duckdb.connect(DB_PATH, read_only=True)
    try:
        # Load from the mart table generated by dbt
        df = con.execute("SELECT * FROM fct_deliveries").fetchdf()
        return df
    except Exception as e:
        st.error(f"Erro ao carregar dados do DuckDB: {e}")
        return None
    finally:
        con.close()

st.title("🚚 Painel de Monitoramento de Entregas")

df = load_data()

if df is not None and not df.empty:
    # Key Metrics
    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.metric("Total de Entregas", len(df))
    with col2:
        st.metric("Atrasos Críticos", len(df[df['priority'] == 'CRITICAL']))
    with col3:
        st.metric("Entregas no Prazo", len(df[df['status'] == 'DELIVERED_ON_TIME']))
    with col4:
        avg_delay = df['delay_minutes'].mean()
        st.metric("Atraso Médio (min)", f"{avg_delay:.1f}" if not pd.isna(avg_delay) else "0")

    # Data Table
    st.subheader("📋 Lista de Entregas")
    
    # Filtering
    status_filter = st.multiselect("Filtrar por Status", options=df['status'].unique(), default=df['status'].unique())
    priority_filter = st.multiselect("Filtrar por Prioridade", options=df['priority'].unique(), default=df['priority'].unique())
    
    filtered_df = df[(df['status'].isin(status_filter)) & (df['priority'].isin(priority_filter))]
    
    st.dataframe(filtered_df, use_container_width=True)

    # Charts
    c1, c2 = st.columns(2)
    with c1:
        st.subheader("Distribuição por Prioridade")
        st.bar_chart(df['priority'].value_counts())
    with c2:
        st.subheader("Status das Entregas")
        st.bar_chart(df['status'].value_counts())

else:
    st.info("Nenhum dado disponível. Aguarde o primeiro job de sincronização ou verifique se o dbt já rodou.")
    if st.button("Tentar recarregar"):
        st.rerun()
